name: cmip7_dreq_env_dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.8
  - bs4
  - coverage
  - openpyxl
  - pooch
  - pytest
  - pyyaml
  - requests
  - pip 
  - pip:
      - .
